# .readthedocs.yaml
version: 2

# Build documentation in the 'docs/' directory with Sphinx
sphinx:
  configuration: source/conf.py

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Set the version of Python and other dependencies to be installed
python:
  version: "3.10.9"
  install:
    - requirements: requirements.txt
    - path: .